import './normalize.css'
import './assets/components.css'
import './assets/form-styles.css'
import './assets/cards-styles.css'
import './assets/components'
import './assets/cards'
import { cardsData } from './assets/cards'
import './style.css'
import './scripts'
import './assets/AttForm'